# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\ResetPassWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResetPassWindow(object):
    def setupUi(self, ResetPassWindow):
        ResetPassWindow.setObjectName("ResetPassWindow")
        ResetPassWindow.resize(380, 430)
        self.BackGroundFrame = QtWidgets.QFrame(ResetPassWindow)
        self.BackGroundFrame.setGeometry(QtCore.QRect(0, 0, 380, 430))
        self.BackGroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BackGroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BackGroundFrame.setObjectName("BackGroundFrame")
        self.TopFrame = QtWidgets.QFrame(self.BackGroundFrame)
        self.TopFrame.setGeometry(QtCore.QRect(0, 0, 380, 50))
        self.TopFrame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.477273, x2:1, y2:0.471591, stop:0 rgba(80, 174, 247, 255), stop:1 rgba(15, 143, 242, 255));\n"
"border: none;")
        self.TopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopFrame.setObjectName("TopFrame")
        self.ResetNameLabel = QtWidgets.QLabel(self.TopFrame)
        self.ResetNameLabel.setGeometry(QtCore.QRect(20, 15, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.ResetNameLabel.setFont(font)
        self.ResetNameLabel.setStyleSheet("background-color: transparent;\n"
"font-size:18px;")
        self.ResetNameLabel.setObjectName("ResetNameLabel")
        self.CloseButton = QtWidgets.QPushButton(self.TopFrame)
        self.CloseButton.setGeometry(QtCore.QRect(330, 10, 30, 30))
        self.CloseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseButton.setStyleSheet("background-color: transparent;")
        self.CloseButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\designer\\../statics/imgs/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CloseButton.setIcon(icon)
        self.CloseButton.setIconSize(QtCore.QSize(23, 23))
        self.CloseButton.setObjectName("CloseButton")
        self.BodyFrame = QtWidgets.QFrame(self.BackGroundFrame)
        self.BodyFrame.setGeometry(QtCore.QRect(0, 50, 380, 380))
        self.BodyFrame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;")
        self.BodyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BodyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BodyFrame.setObjectName("BodyFrame")
        self.TitleLabel = QtWidgets.QLabel(self.BodyFrame)
        self.TitleLabel.setGeometry(QtCore.QRect(79, 20, 221, 29))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size:18px;")
        self.TitleLabel.setObjectName("TitleLabel")
        self.VersionLabel = QtWidgets.QLabel(self.BodyFrame)
        self.VersionLabel.setGeometry(QtCore.QRect(160, 54, 66, 27))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.VersionLabel.setFont(font)
        self.VersionLabel.setStyleSheet("color: rgb(43, 128, 247);\n"
"background-color: rgb(233, 242, 254);\n"
"border-radius: 13;\n"
"font-size:14px;")
        self.VersionLabel.setObjectName("VersionLabel")
        self.OldPassFrame = QtWidgets.QFrame(self.BodyFrame)
        self.OldPassFrame.setGeometry(QtCore.QRect(43, 94, 301, 36))
        self.OldPassFrame.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border: none;")
        self.OldPassFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OldPassFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OldPassFrame.setObjectName("OldPassFrame")
        self.OldPassInput = QtWidgets.QLineEdit(self.OldPassFrame)
        self.OldPassInput.setGeometry(QtCore.QRect(40, 0, 261, 36))
        self.OldPassInput.setStyleSheet("border: none;\n"
"color: black;")
        self.OldPassInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.OldPassInput.setObjectName("OldPassInput")
        self.OldPassIcon = QtWidgets.QLabel(self.OldPassFrame)
        self.OldPassIcon.setGeometry(QtCore.QRect(8, 7, 20, 22))
        self.OldPassIcon.setText("")
        self.OldPassIcon.setPixmap(QtGui.QPixmap(".\\designer\\../statics/imgs/passinput.png"))
        self.OldPassIcon.setScaledContents(True)
        self.OldPassIcon.setObjectName("OldPassIcon")
        self.NewPassFrame = QtWidgets.QFrame(self.BodyFrame)
        self.NewPassFrame.setGeometry(QtCore.QRect(43, 150, 301, 36))
        self.NewPassFrame.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border: none;")
        self.NewPassFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NewPassFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NewPassFrame.setObjectName("NewPassFrame")
        self.NewPassInput = QtWidgets.QLineEdit(self.NewPassFrame)
        self.NewPassInput.setGeometry(QtCore.QRect(40, 0, 261, 36))
        self.NewPassInput.setStyleSheet("color: black;\n"
"border: none;")
        self.NewPassInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.NewPassInput.setObjectName("NewPassInput")
        self.NewPassIcon = QtWidgets.QLabel(self.NewPassFrame)
        self.NewPassIcon.setGeometry(QtCore.QRect(8, 7, 20, 22))
        self.NewPassIcon.setText("")
        self.NewPassIcon.setPixmap(QtGui.QPixmap(".\\designer\\../statics/imgs/passinput.png"))
        self.NewPassIcon.setScaledContents(True)
        self.NewPassIcon.setObjectName("NewPassIcon")
        self.ConfirmButton = QtWidgets.QPushButton(self.BodyFrame)
        self.ConfirmButton.setGeometry(QtCore.QRect(60, 320, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.ConfirmButton.setFont(font)
        self.ConfirmButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ConfirmButton.setStyleSheet("QPushButton{\n"
"    font-size:16px;\n"
"    border: none;\n"
"    border-radius: 15;\n"
"    background-color: rgb(43, 128, 247);\n"
"}\n"
":hover{\n"
"    font-size:16px;\n"
"    background-color: rgb(146, 212, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.CancelButton = QtWidgets.QPushButton(self.BodyFrame)
        self.CancelButton.setGeometry(QtCore.QRect(220, 320, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.CancelButton.setFont(font)
        self.CancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CancelButton.setStyleSheet("QPushButton{\n"
"    font-size:16px;\n"
"    border: none;\n"
"    background-color: rgb(246, 41, 41);    \n"
"    border-radius: 15;\n"
"}\n"
":hover{\n"
"    font-size:16px;\n"
"    background-color: rgb(255, 188, 226);\n"
"}\n"
"\n"
"")
        self.CancelButton.setObjectName("CancelButton")
        self.ConfirmPassFrame = QtWidgets.QFrame(self.BodyFrame)
        self.ConfirmPassFrame.setGeometry(QtCore.QRect(43, 207, 301, 36))
        self.ConfirmPassFrame.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border: none;")
        self.ConfirmPassFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ConfirmPassFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ConfirmPassFrame.setObjectName("ConfirmPassFrame")
        self.ConfirmPassInput = QtWidgets.QLineEdit(self.ConfirmPassFrame)
        self.ConfirmPassInput.setGeometry(QtCore.QRect(40, 0, 261, 36))
        self.ConfirmPassInput.setStyleSheet("color: black;\n"
"border: none;")
        self.ConfirmPassInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ConfirmPassInput.setObjectName("ConfirmPassInput")
        self.ConfirmPassIcon = QtWidgets.QLabel(self.ConfirmPassFrame)
        self.ConfirmPassIcon.setGeometry(QtCore.QRect(8, 7, 20, 22))
        self.ConfirmPassIcon.setText("")
        self.ConfirmPassIcon.setPixmap(QtGui.QPixmap(".\\designer\\../statics/imgs/passinput.png"))
        self.ConfirmPassIcon.setScaledContents(True)
        self.ConfirmPassIcon.setObjectName("ConfirmPassIcon")
        self.label = QtWidgets.QLabel(self.BodyFrame)
        self.label.setGeometry(QtCore.QRect(40, 270, 321, 16))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size:13px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.BodyFrame)
        self.label_2.setGeometry(QtCore.QRect(40, 290, 211, 16))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size:13px;")
        self.label_2.setObjectName("label_2")
        self.MessageLabel1 = QtWidgets.QLabel(self.BodyFrame)
        self.MessageLabel1.setGeometry(QtCore.QRect(50, 130, 291, 16))
        self.MessageLabel1.setStyleSheet("color: red;\n"
"font-size:13px;")
        self.MessageLabel1.setObjectName("MessageLabel1")
        self.MessageLabel2 = QtWidgets.QLabel(self.BodyFrame)
        self.MessageLabel2.setGeometry(QtCore.QRect(50, 190, 291, 16))
        self.MessageLabel2.setStyleSheet("color: red;\n"
"font-size:13px;")
        self.MessageLabel2.setObjectName("MessageLabel2")
        self.MessageLabel3 = QtWidgets.QLabel(self.BodyFrame)
        self.MessageLabel3.setGeometry(QtCore.QRect(50, 240, 291, 16))
        self.MessageLabel3.setStyleSheet("color: red;\n"
"font-size:13px;")
        self.MessageLabel3.setObjectName("MessageLabel3")

        self.retranslateUi(ResetPassWindow)
        QtCore.QMetaObject.connectSlotsByName(ResetPassWindow)

    def retranslateUi(self, ResetPassWindow):
        _translate = QtCore.QCoreApplication.translate
        ResetPassWindow.setWindowTitle(_translate("ResetPassWindow", "Form"))
        self.ResetNameLabel.setText(_translate("ResetPassWindow", "修改密码"))
        self.TitleLabel.setText(_translate("ResetPassWindow", "国联恶意代码辅助监测系统"))
        self.VersionLabel.setText(_translate("ResetPassWindow", "   主机版"))
        self.OldPassInput.setPlaceholderText(_translate("ResetPassWindow", "旧密码"))
        self.NewPassInput.setPlaceholderText(_translate("ResetPassWindow", "新密码"))
        self.ConfirmButton.setText(_translate("ResetPassWindow", "确认"))
        self.CancelButton.setText(_translate("ResetPassWindow", "取消"))
        self.ConfirmPassInput.setPlaceholderText(_translate("ResetPassWindow", "确认密码"))
        self.label.setText(_translate("ResetPassWindow", "新密码至少8个字符,其中数字至少1个,大写字母至少1个"))
        self.label_2.setText(_translate("ResetPassWindow", "小写字母至少1个，特殊字符至少1个"))
        self.MessageLabel1.setText(_translate("ResetPassWindow", "MessageLabel1"))
        self.MessageLabel2.setText(_translate("ResetPassWindow", "MessageLabel2"))
        self.MessageLabel3.setText(_translate("ResetPassWindow", "MessageLabel3"))
